### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by survivorm** [guyskk/validr#19]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qqy3vem8/validr/setup.py", line 8, in <module>
        long_description = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 576: ordinal not in range(128)

Looks like with some system encodings istallation is broken.
i suggest replacing line 7 at setup.py
```python
with open(os.path.join(dirname(__file__), 'README.md')) as f:
```
with

```python
with open(os.path.join(dirname(__file__), 'README.md'), 'r', 'utf-8') as f:
```

**Comment by guyskk** [comment]
OK, good suggestion!
